import { BookMetadata } from '../src/types';

export const booksMetadata: BookMetadata[] = [
  {
    id: 'zara-missing-moonbeam',
    title: 'Zara and the Missing Moonbeam',
    slug: 'zara-and-the-missing-moonbeam',
    author: 'LittleReads Editorial Team',
    description: 'When the moonbeam that lights up the magical garden of Nkemdilim disappears, brave young Zara must embark on a quest through starlit paths and whispering rivers to find it. Along the way, she meets a wise tortoise, a playful firefly, and learns that sometimes the answers we seek are closer than we think. A heartwarming tale about curiosity, courage, and the power of problem solving.',
    short_description: 'A brave girl embarks on a magical quest to find the missing moonbeam.',
    category: 'Adventure',
    category_slug: 'adventure',
    age_min: 5,
    age_max: 7,
    reading_level: 'Beginner',
    page_count: 16,
    reading_time: '8 min',
    price: 1500,
    learning_outcomes: [
      'Problem solving through creative thinking',
      'Courage in the face of the unknown',
      'The value of asking questions',
      'Kindness to strangers on a journey',
      'Understanding that answers are often close by',
    ],
    keywords: ['adventure', 'moon', 'courage', 'problem solving', 'magical quest', 'bedtime'],
    featured: true,
    cover_path: 'generated/covers/zara-and-the-missing-moonbeam.png',
    pdf_path: 'generated/ebooks/zara-and-the-missing-moonbeam.pdf',
  },
  {
    id: 'tobi-amazing-robot',
    title: "Tobi's Amazing Robot",
    slug: 'tobis-amazing-robot',
    author: 'LittleReads Editorial Team',
    description: 'Tobi has always loved taking things apart and putting them back together. When his teacher announces a science fair, Tobi decides to build a robot from recycled materials. After many failed attempts and a few funny mishaps, Tobi discovers that perseverance and creativity can turn junk into something amazing. This story introduces basic engineering concepts while celebrating the spirit of invention.',
    short_description: 'A young inventor builds a robot from recycled materials for the science fair.',
    category: 'Science & Technology',
    category_slug: 'science-technology',
    age_min: 6,
    age_max: 8,
    reading_level: 'Beginner',
    page_count: 18,
    reading_time: '10 min',
    price: 1800,
    learning_outcomes: [
      'Basic engineering and design thinking',
      'Perseverance through failure',
      'Recycling and sustainability',
      'Creativity with everyday materials',
      'The joy of building and inventing',
    ],
    keywords: ['robot', 'invention', 'STEM', 'recycling', 'engineering', 'science fair'],
    featured: true,
    cover_path: 'generated/covers/tobis-amazing-robot.png',
    pdf_path: 'generated/ebooks/tobis-amazing-robot.pdf',
  },
  {
    id: 'amara-talking-baobab',
    title: 'Amara and the Talking Baobab',
    slug: 'amara-and-the-talking-baobab',
    author: 'LittleReads Editorial Team',
    description: 'Deep in the village of Oke-Oye, there stands an ancient baobab tree that only speaks to those who truly listen. When young Amara sits beneath its branches after helping her grandmother, she discovers the tree has stories to share — stories of the village, of wisdom, and of the importance of respecting nature. This beautiful African tale teaches children about the value of listening and the deep connection between people and the natural world.',
    short_description: 'A girl discovers an ancient tree with wisdom to share about nature and respect.',
    category: 'African Stories',
    category_slug: 'african-stories',
    age_min: 6,
    age_max: 8,
    reading_level: 'Beginner',
    page_count: 18,
    reading_time: '10 min',
    price: 1500,
    learning_outcomes: [
      'The importance of listening carefully',
      'Respect for nature and the environment',
      'Value of African oral traditions',
      'Wisdom passed through generations',
      'Connection between people and nature',
    ],
    keywords: ['baobab', 'African', 'wisdom', 'nature', 'listening', 'village'],
    featured: true,
    cover_path: 'generated/covers/amara-and-the-talking-baobab.png',
    pdf_path: 'generated/ebooks/amara-and-the-talking-baobab.pdf',
  },
  {
    id: 'little-lion-learned-to-listen',
    title: 'The Little Lion Who Learned to Listen',
    slug: 'the-little-lion-who-learned-to-listen',
    author: 'LittleReads Editorial Team',
    description: 'Leo the little lion cub is always in a rush. He never listens to his mother, his teacher, or his friends. When his impatience leads him into a sticky situation in the savanna, Leo must learn the true meaning of listening. With the help of wise elephant and patient hippo, Leo discovers that listening is not just about hearing words — it is about caring.',
    short_description: 'A lion cub learns that listening is about caring for others.',
    category: 'Life Skills',
    category_slug: 'life-skills',
    age_min: 5,
    age_max: 7,
    reading_level: 'Beginner',
    page_count: 14,
    reading_time: '7 min',
    price: 1200,
    learning_outcomes: [
      'Active listening skills',
      'Empathy and caring for others',
      'Patience and self-control',
      'Understanding consequences of actions',
      'Respect for others\' words',
    ],
    keywords: ['listening', 'empathy', 'lion', 'patience', 'savanna', 'life skills'],
    featured: false,
    cover_path: 'generated/covers/the-little-lion-who-learned-to-listen.png',
    pdf_path: 'generated/ebooks/the-little-lion-who-learned-to-listen.pdf',
  },
  {
    id: 'adas-first-day-school',
    title: "Ada's First Day of School",
    slug: 'adas-first-day-of-school',
    author: 'LittleReads Editorial Team',
    description: 'It is Ada\'s very first day of school, and she is nervous. What if the other children do not like her? What if she cannot find her classroom? But when Ada arrives, she discovers that everyone feels a little nervous on their first day. With the help of her new teacher and a kind classmate named Chukwu, Ada finds the courage to be herself. A gentle, reassuring story for children starting school.',
    short_description: 'A nervous girl finds courage on her first day of school.',
    category: 'Life Skills',
    category_slug: 'life-skills',
    age_min: 5,
    age_max: 6,
    reading_level: 'Beginner',
    page_count: 12,
    reading_time: '6 min',
    price: 1000,
    learning_outcomes: [
      'Overcoming nervousness in new situations',
      'Building confidence and self-esteem',
      'Making new friends',
      'Understanding that everyone feels nervous sometimes',
      'The excitement of learning new things',
    ],
    keywords: ['school', 'confidence', 'first day', 'friends', 'nervous', 'courage'],
    featured: true,
    cover_path: 'generated/covers/adas-first-day-of-school.png',
    pdf_path: 'generated/ebooks/adas-first-day-of-school.pdf',
  },
  {
    id: 'adventure-inside-my-computer',
    title: 'The Adventure Inside My Computer',
    slug: 'the-adventure-inside-my-computer',
    author: 'LittleReads Editorial Team',
    description: 'What happens when you turn on a computer? Where does all the information go? In this imaginative story, siblings Emeka and Zainab shrink down to the size of a pixel and travel inside a computer. They explore the motherboard, race through the RAM, meet the hard drive guardian, and discover how data travels through circuits. A fun and educational journey that makes computer science accessible and exciting.',
    short_description: 'Two siblings shrink and explore the inside of a computer.',
    category: 'Education',
    category_slug: 'education',
    age_min: 7,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 22,
    reading_time: '14 min',
    price: 2000,
    learning_outcomes: [
      'Understanding what a computer does',
      'Basic hardware concepts (RAM, CPU, hard drive)',
      'How data moves through circuits',
      'The difference between hardware and software',
      'Curiosity about technology',
    ],
    keywords: ['computer', 'technology', 'hardware', 'STEM', 'pixel', 'data'],
    featured: false,
    cover_path: 'generated/covers/the-adventure-inside-my-computer.png',
    pdf_path: 'generated/ebooks/the-adventure-inside-my-computer.pdf',
  },
  {
    id: 'kemi-secret-garden',
    title: 'Kemi and the Secret Garden',
    slug: 'kemi-and-the-secret-garden',
    author: 'LittleReads Editorial Team',
    description: 'When Kemi moves to a new house, she discovers a hidden garden behind a crumbling wall. Inside, she finds flowers she has never seen, a small pond with tadpoles, and a garden that has been waiting for someone to care for it. As Kemi tends to the garden, she learns about ecosystems, responsibility, and how every small creature plays a part in nature\'s beautiful web.',
    short_description: 'A girl discovers a hidden garden and learns about nature and responsibility.',
    category: 'Nature',
    category_slug: 'nature',
    age_min: 6,
    age_max: 8,
    reading_level: 'Beginner',
    page_count: 18,
    reading_time: '10 min',
    price: 1500,
    learning_outcomes: [
      'Understanding ecosystems and biodiversity',
      'Responsibility and caring for living things',
      'Patience in nurturing growth',
      'The interconnectedness of nature',
      'Gardening and plant life cycles',
    ],
    keywords: ['garden', 'plants', 'ecosystem', 'nature', 'responsibility', 'biodiversity'],
    featured: false,
    cover_path: 'generated/covers/kemi-and-the-secret-garden.png',
    pdf_path: 'generated/ebooks/kemi-and-the-secret-garden.pdf',
  },
  {
    id: 'why-does-rain-fall',
    title: 'Why Does the Rain Fall?',
    slug: 'why-does-the-rain-fall',
    author: 'LittleReads Editorial Team',
    description: 'Little Kofi wonders why the rain falls from the sky. His grandmother tells him the story of the water cycle — how water travels from rivers and oceans up to the clouds, how clouds become heavy with rain, and how the rain falls back to earth to fill the rivers again. Through Kofi\'s questions and his grandmother\'s gentle answers, children discover the science behind one of nature\'s most common phenomena.',
    short_description: 'A curious boy learns about the water cycle from his grandmother.',
    category: 'Science',
    category_slug: 'science',
    age_min: 7,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 16,
    reading_time: '10 min',
    price: 1800,
    learning_outcomes: [
      'Understanding the water cycle',
      'Evaporation, condensation, and precipitation',
      'Where rain comes from',
      'The importance of water on Earth',
      'Asking questions and seeking answers',
    ],
    keywords: ['rain', 'water cycle', 'weather', 'science', 'clouds', 'environment'],
    featured: false,
    cover_path: 'generated/covers/why-does-the-rain-fall.png',
    pdf_path: 'generated/ebooks/why-does-the-rain-fall.pdf',
  },
  {
    id: 'boy-befriended-numbers',
    title: 'The Boy Who Befriended Numbers',
    slug: 'the-boy-who-befriended-numbers',
    author: 'LittleReads Editorial Team',
    description: 'Jide thinks maths is boring and hard. Then one day, the numbers start talking to him! One is adventurous, Seven is mysterious, and Zero teaches Jide about the beauty of starting fresh. As Jide befriends each number, he discovers that mathematics is not about memorising formulas — it is about patterns, puzzles, and the fun of figuring things out. A story that makes maths less intimidating and more delightful.',
    short_description: 'A boy discovers maths is fun when the numbers come alive.',
    category: 'Education',
    category_slug: 'education',
    age_min: 7,
    age_max: 9,
    reading_level: 'Intermediate',
    page_count: 20,
    reading_time: '12 min',
    price: 1800,
    learning_outcomes: [
      'Maths can be fun and creative',
      'Number recognition and basic operations',
      'Pattern recognition',
      'Growth mindset towards learning',
      'Finding beauty in mathematics',
    ],
    keywords: ['maths', 'numbers', 'education', 'patterns', 'creativity', 'STEM'],
    featured: false,
    cover_path: 'generated/covers/the-boy-who-befriended-numbers.png',
    pdf_path: 'generated/ebooks/the-boy-who-befriended-numbers.pdf',
  },
  {
    id: 'nias-big-idea',
    title: "Nia's Big Idea",
    slug: 'nias-big-idea',
    author: 'LittleReads Editorial Team',
    description: 'Nia notices that the women in her neighbourhood spend hours fetching water from far away. One day, she has a big idea: what if she could build a simple water collection system using what she has? With determination, creativity, and the help of her community, Nia learns that entrepreneurship is about seeing a problem and finding a solution. This inspiring story introduces children to the concepts of innovation, problem-solving, and social enterprise.',
    short_description: 'A young girl solves a community problem through innovation and enterprise.',
    category: 'Entrepreneurship',
    category_slug: 'entrepreneurship',
    age_min: 8,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 20,
    reading_time: '12 min',
    price: 2000,
    learning_outcomes: [
      'Identifying problems and creating solutions',
      'Basic entrepreneurship concepts',
      'Community collaboration',
      'Innovation with available resources',
      'Social responsibility through business',
    ],
    keywords: ['entrepreneurship', 'innovation', 'community', 'problem solving', 'water', 'Africa'],
    featured: false,
    cover_path: 'generated/covers/nias-big-idea.png',
    pdf_path: 'generated/ebooks/nias-big-idea.pdf',
  },
  {
    id: 'kindness-jar',
    title: 'The Kindness Jar',
    slug: 'the-kindness-jar',
    author: 'LittleReads Editorial Team',
    description: 'When Amara starts at a new school, her mother gives her a special jar. Every time Amara does something kind, she puts a stone in the jar. At first, the jar feels heavy and the stones seem small. But as the days pass, Amara discovers that kindness grows — it multiplies, it spreads, and it fills not just the jar but the hearts of everyone around her. A gentle and powerful story about the ripple effect of kindness.',
    short_description: 'A girl fills a jar with stones for every kind act she performs.',
    category: 'Friendship',
    category_slug: 'friendship',
    age_min: 5,
    age_max: 7,
    reading_level: 'Beginner',
    page_count: 14,
    reading_time: '7 min',
    price: 1200,
    learning_outcomes: [
      'Understanding the power of kindness',
      'How small acts create big changes',
      'Building positive habits',
      'Empathy and helping others',
      'The ripple effect of good deeds',
    ],
    keywords: ['kindness', 'friendship', 'empathy', 'school', 'habits', 'community'],
    featured: true,
    cover_path: 'generated/covers/the-kindness-jar.png',
    pdf_path: 'generated/ebooks/the-kindness-jar.pdf',
  },
  {
    id: 'chidi-trip-to-space',
    title: "Chidi's Trip to Space",
    slug: 'chidis-trip-to-space',
    author: 'LittleReads Editorial Team',
    description: 'Chidi dreams of being an astronaut. One night, while stargazing with his father, a shooting star grants his wish. He blasts off in a rocket and visits every planet in our solar system. From the fiery surface of Mercury to the icy rings of Saturn, Chidi discovers that each planet is unique and special. A thrilling space adventure that teaches children about the solar system while igniting their imagination.',
    short_description: 'A boy visits every planet in the solar system in a dream rocket.',
    category: 'Science',
    category_slug: 'science',
    age_min: 7,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 22,
    reading_time: '14 min',
    price: 2000,
    learning_outcomes: [
      'Names and order of the planets',
      'Basic facts about each planet',
      'Understanding gravity and space',
      'The sun as the centre of our solar system',
      'Inspiration for space exploration',
    ],
    keywords: ['space', 'planets', 'solar system', 'astronomy', 'rocket', 'STEM'],
    featured: true,
    cover_path: 'generated/covers/chidis-trip-to-space.png',
    pdf_path: 'generated/ebooks/chidis-trip-to-space.pdf',
  },
  {
    id: 'village-saved-water',
    title: 'The Village That Saved Water',
    slug: 'the-village-that-saved-water',
    author: 'LittleReads Editorial Team',
    description: 'In the village of Ile-Iwa, the well is running dry. The elders call a meeting, but no one knows what to do. It is young Binta who suggests they work together to conserve water — fixing leaky pots, collecting rainwater, planting drought-resistant crops, and sharing what they have. As the village follows Binta\'s plan, they discover that working together not only saves water but strengthens their community.',
    short_description: 'A young girl helps her village conserve water through teamwork.',
    category: 'Environment',
    category_slug: 'environment',
    age_min: 7,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 18,
    reading_time: '11 min',
    price: 1800,
    learning_outcomes: [
      'Water conservation methods',
      'Community problem solving',
      'Environmental responsibility',
      'Rainwater harvesting',
      'The value of sharing resources',
    ],
    keywords: ['water conservation', 'environment', 'community', 'sustainability', 'Africa', 'teamwork'],
    featured: false,
    cover_path: 'generated/covers/the-village-that-saved-water.png',
    pdf_path: 'generated/ebooks/the-village-that-saved-water.pdf',
  },
  {
    id: 'maya-brave-little-seed',
    title: 'Maya and the Brave Little Seed',
    slug: 'maya-and-the-brave-little-seed',
    author: 'LittleReads Editorial Team',
    description: 'Maya plants a tiny seed in her garden and waits. Day after day, she waters it, talks to it, and wonders if anything will ever happen. The seed feels scared underground — it is dark and lonely. But with patience, encouragement, and a little bit of rain, the seed begins to grow. Together, Maya and the seed learn that beautiful things take time, and that growth requires patience, faith, and care.',
    short_description: 'A girl and her seed learn together about patience and growth.',
    category: 'Nature',
    category_slug: 'nature',
    age_min: 5,
    age_max: 7,
    reading_level: 'Beginner',
    page_count: 12,
    reading_time: '6 min',
    price: 1200,
    learning_outcomes: [
      'Patience and delayed gratification',
      'Plant growth and life cycles',
      'Caring for living things',
      'Understanding that growth takes time',
      'The joy of nurturing something',
    ],
    keywords: ['plants', 'patience', 'growth', 'garden', 'seeds', 'nature'],
    featured: false,
    cover_path: 'generated/covers/maya-and-the-brave-little-seed.png',
    pdf_path: 'generated/ebooks/maya-and-the-brave-little-seed.pdf',
  },
  {
    id: 'my-first-internet-safety',
    title: 'My First Internet Safety Book',
    slug: 'my-first-internet-safety-book',
    author: 'LittleReads Editorial Team',
    description: 'The internet is a wonderful place full of games, videos, and learning. But it is also a place where children need to be careful. In this important and engaging book, children learn about staying safe online through relatable stories and characters. They discover what personal information is, why passwords matter, how to deal with online strangers, when to ask an adult for help, and what cyberbullying looks like. Written in a friendly, non-frightening way.',
    short_description: 'A friendly guide to staying safe on the internet.',
    category: 'Technology',
    category_slug: 'technology',
    age_min: 7,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 20,
    reading_time: '12 min',
    price: 2500,
    learning_outcomes: [
      'Protecting personal information online',
      'Creating and managing passwords',
      'Recognising online strangers',
      'When to ask an adult for help',
      'Understanding and preventing cyberbullying',
    ],
    keywords: ['internet safety', 'online safety', 'passwords', 'cyberbullying', 'technology', 'digital literacy'],
    featured: false,
    cover_path: 'generated/covers/my-first-internet-safety-book.png',
    pdf_path: 'generated/ebooks/my-first-internet-safety-book.pdf',
  },
  {
    id: 'three-friends-broken-bridge',
    title: 'The Three Friends and the Broken Bridge',
    slug: 'the-three-friends-and-the-broken-bridge',
    author: 'LittleReads Editorial Team',
    description: 'Folake, Ibrahim, and Chinwe are best friends. One rainy season, the bridge across the river breaks, and no one can cross. Each friend tries to fix it alone and fails. But when they combine their different strengths — Folake\'s planning, Ibrahim\'s strength, and Chinwe\'s creativity — they build a bridge stronger than the old one. A powerful story about teamwork, collaboration, and how our differences make us stronger together.',
    short_description: 'Three friends learn that teamwork builds stronger bridges.',
    category: 'Friendship',
    category_slug: 'friendship',
    age_min: 6,
    age_max: 8,
    reading_level: 'Beginner',
    page_count: 16,
    reading_time: '9 min',
    price: 1500,
    learning_outcomes: [
      'Teamwork and collaboration',
      'Using individual strengths for a common goal',
      'Problem solving through cooperation',
      'Respecting different abilities',
      'Building stronger solutions together',
    ],
    keywords: ['teamwork', 'friendship', 'collaboration', 'bridge', 'problem solving', 'diversity'],
    featured: false,
    cover_path: 'generated/covers/the-three-friends-and-the-broken-bridge.png',
    pdf_path: 'generated/ebooks/the-three-friends-and-the-broken-bridge.pdf',
  },
  {
    id: 'day-became-young-scientist',
    title: 'The Day I Became a Young Scientist',
    slug: 'the-day-i-became-a-young-scientist',
    author: 'LittleReads Editorial Team',
    description: 'When Faridah\'s teacher announces a science project, Faridah feels lost. She does not know where to start. But then she remembers the scientific method: observe, question, hypothesise, experiment, and conclude. Through a series of fun experiments — testing which soil makes plants grow fastest, checking if music helps plants grow, and measuring shadows through the day — Faridah discovers that being a scientist is simply about being curious and testing your ideas.',
    short_description: 'A girl discovers the scientific method through fun experiments.',
    category: 'Science',
    category_slug: 'science',
    age_min: 8,
    age_max: 10,
    reading_level: 'Advanced',
    page_count: 22,
    reading_time: '14 min',
    price: 2000,
    learning_outcomes: [
      'The scientific method (observe, question, hypothesise, experiment, conclude)',
      'Designing simple experiments',
      'Recording and analysing results',
      'Critical thinking and evidence',
      'Science is for everyone',
    ],
    keywords: ['scientific method', 'experiments', 'science', 'STEM', 'observation', 'hypothesis'],
    featured: false,
    cover_path: 'generated/covers/the-day-i-became-a-young-scientist.png',
    pdf_path: 'generated/ebooks/the-day-i-became-a-young-scientist.pdf',
  },
  {
    id: 'amina-learns-to-save',
    title: 'Amina Learns to Save',
    slug: 'amina-learns-to-save',
    author: 'LittleReads Editorial Team',
    description: 'Amina receives her weekly pocket money and spends it all on sweets and toys. When she sees a beautiful book she really wants, she has no money left. Her mother teaches her about saving — the difference between needs and wants, how to set goals, and the satisfaction of watching money grow. Over several weeks, Amina learns that saving is not about saying no to everything, but about choosing what matters most.',
    short_description: 'A girl learns the value of saving money for what matters.',
    category: 'Money Skills',
    category_slug: 'money-skills',
    age_min: 7,
    age_max: 10,
    reading_level: 'Intermediate',
    page_count: 16,
    reading_time: '10 min',
    price: 2000,
    learning_outcomes: [
      'Understanding saving vs spending',
      'Distinguishing between needs and wants',
      'Setting financial goals',
      'Delayed gratification',
      'Basic money management skills',
    ],
    keywords: ['money', 'saving', 'spending', 'financial literacy', 'goals', 'budgeting'],
    featured: false,
    cover_path: 'generated/covers/amina-learns-to-save.png',
    pdf_path: 'generated/ebooks/amina-learns-to-save.pdf',
  },
  {
    id: 'mystery-rainbow-hill',
    title: 'The Mystery of Rainbow Hill',
    slug: 'the-mystery-of-rainbow-hill',
    author: 'LittleReads Editorial Team',
    description: 'Legend says that Rainbow Hill glows with every colour of the rainbow once a year. No one has ever seen it happen. When best friends Tolu and Sam decide to investigate, they find clues hidden in old books, follow mysterious maps, and use logical thinking to solve puzzles. As they climb higher, they discover that the real treasure is not what glows on the hill, but the adventure and the friendship they share. A mystery story that celebrates logical thinking.',
    short_description: 'Two friends solve clues and puzzles on a mysterious hill.',
    category: 'Adventure',
    category_slug: 'adventure',
    age_min: 7,
    age_max: 9,
    reading_level: 'Intermediate',
    page_count: 20,
    reading_time: '12 min',
    price: 1800,
    learning_outcomes: [
      'Logical thinking and deduction',
      'Following clues and evidence',
      'Critical thinking skills',
      'Map reading basics',
      'The value of friendship during adventures',
    ],
    keywords: ['mystery', 'adventure', 'logic', 'puzzles', 'detective', 'friendship'],
    featured: false,
    cover_path: 'generated/covers/the-mystery-of-rainbow-hill.png',
    pdf_path: 'generated/ebooks/the-mystery-of-rainbow-hill.pdf',
  },
  {
    id: 'goodnight-little-explorer',
    title: 'Goodnight, Little Explorer',
    slug: 'goodnight-little-explorer',
    author: 'LittleReads Editorial Team',
    description: 'As the sun sets, a little explorer sets out on one last adventure — a journey through the imagination. She sails across a chocolate river, climbs a mountain made of pillows, dances with fireflies in a glowing forest, and meets a friendly owl who tells her stories of the stars. Each adventure grows softer and quieter until the little explorer drifts to sleep, dreaming of tomorrow\'s adventures. A calming bedtime story designed to help children wind down.',
    short_description: 'A calming bedtime adventure through an imaginary world.',
    category: 'Bedtime Stories',
    category_slug: 'bedtime-stories',
    age_min: 5,
    age_max: 7,
    reading_level: 'Beginner',
    page_count: 12,
    reading_time: '8 min',
    price: 1200,
    learning_outcomes: [
      'Calming bedtime routine',
      'Imagination and creativity',
      'Nature appreciation through storytelling',
      'Emotional regulation before sleep',
      'The joy of peaceful dreaming',
    ],
    keywords: ['bedtime', 'sleep', 'imagination', 'adventure', 'calm', 'dreams'],
    featured: true,
    cover_path: 'generated/covers/goodnight-little-explorer.png',
    pdf_path: 'generated/ebooks/goodnight-little-explorer.pdf',
  },
];

// Sample reviews for seed data
export const sampleReviews = [
  { book_slug: 'zara-and-the-missing-moonbeam', name: 'Adaeze', rating: 5, title: 'My daughter loves this!', content: 'We read this every night. The story is gentle and beautiful. Zara is a wonderful role model.' },
  { book_slug: 'zara-and-the-missing-moonbeam', name: 'Emeka', rating: 4, title: 'Great bedtime story', content: 'Nice story with a good message about problem solving. My son asks to read it again and again.' },
  { book_slug: 'tobis-amazing-robot', name: 'Funke', rating: 5, title: 'Inspired my son to build!', content: 'After reading this, my son started building robots from cardboard boxes. Educational and fun!' },
  { book_slug: 'tobis-amazing-robot', name: 'Kemi', rating: 5, title: 'Perfect for young inventors', content: 'My students loved this book. It makes engineering feel accessible and exciting for children.' },
  { book_slug: 'amara-and-the-talking-baobab', name: 'Chinwe', rating: 5, title: 'Beautiful African tale', content: 'Finally, a children\'s book that celebrates African stories. My children love the wisdom of the baobab.' },
  { book_slug: 'adas-first-day-of-school', name: 'Blessing', rating: 5, title: 'Helped with my daughter\'s anxiety', content: 'My daughter was so nervous about starting school. This book helped her feel brave. Highly recommend.' },
  { book_slug: 'the-kindness-jar', name: 'Tunde', rating: 4, title: 'Lovely message', content: 'A simple but powerful story. We started our own kindness jar at home after reading this.' },
  { book_slug: 'chidis-trip-to-space', name: 'Ngozi', rating: 5, title: 'Now he wants to be an astronaut', content: 'My son asks about planets every day now. The space facts are presented in a fun, easy way.' },
  { book_slug: 'goodnight-little-explorer', name: 'Amina', rating: 5, title: 'Perfect bedtime story', content: 'The perfect length and tone for bedtime. My daughter falls asleep smiling every time.' },
  { book_slug: 'goodnight-little-explorer', name: 'Yusuf', rating: 4, title: 'Calm and sweet', content: 'Gentle story that helps my children wind down. The illustrations in our imagination are wonderful.' },
  { book_slug: 'my-first-internet-safety-book', name: 'Grace', rating: 5, title: 'Essential reading', content: 'Every parent should read this with their child. It covers online safety without being scary.' },
  { book_slug: 'my-first-internet-safety-book', name: 'Oluwaseun', rating: 5, title: 'Important for today\'s kids', content: 'Finally a book that teaches internet safety in a way children understand. Well written.' },
  { book_slug: 'mystery-rainbow-hill', name: 'Doris', rating: 4, title: 'Fun mystery story', content: 'My daughter loved solving the clues along with Tolu and Sam. Great for developing logical thinking.' },
  { book_slug: 'amina-learns-to-save', name: 'Maryam', rating: 5, title: 'Changed our pocket money routine', content: 'Now Amina (yes, same name!) saves her pocket money wisely. Great financial literacy for children.' },
  { book_slug: 'the-village-that-saved-water', name: 'Ibrahim', rating: 4, title: 'Important environmental message', content: 'Teaches water conservation in a way that is relevant for African children. Well done.' },
];
