import fs from 'fs';
import path from 'path';
import { booksMetadata } from '../content/books-metadata';

const COVERS_DIR = path.join(process.cwd(), 'generated', 'covers');
const PDFS_DIR = path.join(process.cwd(), 'generated', 'ebooks');

// Minimum sizes to pass validation
const MIN_PDF_BYTES = 5_000;       // 5 KB — a real multi-page PDF
const MIN_COVER_BYTES = 200;        // 200 B — a real SVG cover
const MIN_PDF_PAGES = 6;            // Every ebook has ≥6 pages (cover + title + copyright + story + learning + questions + end)

interface ValidationRow {
  title: string;
  metadata: boolean;
  cover: boolean;
  coverSize: string;
  pdf: boolean;
  pdfSize: string;
  validPdf: boolean;
  pageCount: number;
  titleInPdf: boolean;
  brandingInPdf: boolean;
  wordCount: number;
  price: number;
  category: string;
  ageRange: string;
  slug: string;
  status: string;
  issues: string[];
}

// ── Helpers ──────────────────────────────────────────────────

function countWords(text: string): number {
  return text.split(/\s+/).filter(w => w.length > 0).length;
}

function isValidPdfHeader(buffer: Buffer): boolean {
  return (
    buffer.length > 4 &&
    buffer[0] === 0x25 && // %
    buffer[1] === 0x50 && // P
    buffer[2] === 0x44 && // D
    buffer[3] === 0x46    // F
  );
}

/**
 * Count pages in a PDF by scanning for the /Count entry in the
 * page-tree root object (the highest /Count value in the file).
 * This is a lightweight heuristic that avoids pulling in a heavy
 * PDF parser.
 */
function countPdfPages(buffer: Buffer): number {
  const str = buffer.toString('latin1');
  // Match all /Count <number> entries — the page-tree root has the total
  const matches = str.match(/\/Count\s+(\d+)/g);
  if (!matches || matches.length === 0) return 0;
  let maxCount = 0;
  for (const m of matches) {
    const n = parseInt(m.replace(/\/Count\s+/, ''), 10);
    if (n > maxCount) maxCount = n;
  }
  return maxCount;
}

/**
 * Check whether a specific string (case-insensitive) appears in the
 * PDF binary content. PDFs generated by pdfkit embed text as plain
 * strings in content streams (possibly compressed, but often
 * readable in the raw buffer).
 */
function pdfContainsText(buffer: Buffer, needle: string): boolean {
  // First check raw buffer (works for uncompressed text)
  if (buffer.includes(Buffer.from(needle, 'latin1'))) return true;

  // Also try the latin1 string representation
  const str = buffer.toString('latin1');
  if (str.toLowerCase().includes(needle.toLowerCase())) return true;

  // Try UTF-8 as a fallback (for escaped sequences)
  try {
    const utf8 = buffer.toString('utf-8');
    if (utf8.toLowerCase().includes(needle.toLowerCase())) return true;
  } catch {
    // ignore encoding errors
  }

  return false;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return bytes + 'B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + 'KB';
  return (bytes / (1024 * 1024)).toFixed(1) + 'MB';
}

// ── Validation ───────────────────────────────────────────────

function validateAll(): ValidationRow[] {
  const results: ValidationRow[] = [];

  for (const book of booksMetadata) {
    const issues: string[] = [];

    // ── Metadata ──
    const hasMetadata = !!(
      book.title &&
      book.slug &&
      book.price > 0 &&
      book.category &&
      book.age_min &&
      book.age_max
    );

    // ── Cover ──
    const coverPath = path.join(COVERS_DIR, `${book.slug}.svg`);
    const coverExists = fs.existsSync(coverPath);
    let coverSize = 'N/A';
    if (coverExists) {
      const coverStat = fs.statSync(coverPath);
      coverSize = formatBytes(coverStat.size);
      if (coverStat.size === 0) {
        issues.push('Cover is empty');
      }
      if (coverStat.size < MIN_COVER_BYTES) {
        issues.push(`Cover too small (${coverSize}), likely a placeholder`);
      }
      // Validate SVG structure
      const coverContent = fs.readFileSync(coverPath, 'utf-8');
      if (!coverContent.includes('<svg') || !coverContent.includes('</svg>')) {
        issues.push('Cover SVG invalid');
      }
    } else {
      issues.push('Cover missing');
    }

    // ── PDF ──
    const pdfPath = path.join(PDFS_DIR, `${book.slug}.pdf`);
    const pdfExists = fs.existsSync(pdfPath);
    let pdfSize = 'N/A';
    let validPdf = false;
    let pageCount = 0;
    let titleInPdf = false;
    let brandingInPdf = false;

    if (pdfExists) {
      const pdfStat = fs.statSync(pdfPath);
      pdfSize = formatBytes(pdfStat.size);

      // Check: non-trivial file size
      if (pdfStat.size === 0) {
        issues.push('PDF is empty (0 bytes)');
      } else if (pdfStat.size < MIN_PDF_BYTES) {
        issues.push(
          `PDF suspiciously small (${pdfSize}), expected ≥${formatBytes(MIN_PDF_BYTES)} for a real ebook`
        );
      }

      // Read full buffer for content checks
      const pdfBuffer = fs.readFileSync(pdfPath);

      // Check: valid PDF header
      validPdf = isValidPdfHeader(pdfBuffer);
      if (!validPdf) {
        issues.push('PDF header invalid (not a real PDF)');
      }

      // Check: meaningful page count
      pageCount = countPdfPages(pdfBuffer);
      if (pageCount === 0) {
        issues.push('Could not determine page count from PDF');
      } else if (pageCount < MIN_PDF_PAGES) {
        issues.push(
          `Page count too low (${pageCount}), expected ≥${MIN_PDF_PAGES} for a complete ebook`
        );
      }

      // Check: expected book title present in PDF content
      titleInPdf = pdfContainsText(pdfBuffer, book.title);
      if (!titleInPdf) {
        issues.push(`Book title "${book.title}" not found in PDF content`);
      }

      // Check: LittleReads branding present
      brandingInPdf = pdfContainsText(pdfBuffer, 'LittleReads');
      if (!brandingInPdf) {
        issues.push('LittleReads branding not found in PDF');
      }

      // Check: not a placeholder — verify there is actual story text
      // by looking for a distinctive phrase from the description
      // (first 30 chars of description stripped of punctuation)
      const descSnippet = book.description
        .replace(/[^a-zA-Z\s]/g, '')
        .split(/\s+/)
        .slice(0, 8)
        .join(' ');
      if (descSnippet.length > 5) {
        // We search for a few key words from the description
        const descWords = descSnippet.split(/\s+/).filter(w => w.length > 3);
        const foundWords = descWords.filter(w => pdfContainsText(pdfBuffer, w));
        if (foundWords.length < 2) {
          issues.push(
            'PDF does not contain expected story content (description keywords not found)'
          );
        }
      }
    } else {
      issues.push('PDF missing');
    }

    // ── Word count in description (manuscript proxy) ──
    const wordCount = countWords(book.description);

    // ── Duplicate slug check ──
    const slugs = booksMetadata.map(b => b.slug);
    const duplicateSlugs = slugs.filter(s => s === book.slug);
    if (duplicateSlugs.length > 1) {
      issues.push('Duplicate slug');
    }

    // ── Status ──
    let status = 'PASS';
    if (!hasMetadata) status = 'FAIL - metadata';
    else if (!coverExists) status = 'FAIL - cover';
    else if (!pdfExists) status = 'FAIL - pdf';
    else if (!validPdf) status = 'FAIL - pdf invalid';
    else if (pageCount < MIN_PDF_PAGES) status = 'FAIL - pdf too short';
    else if (!titleInPdf) status = 'FAIL - title missing from pdf';
    else if (issues.length > 0) status = 'WARN';
    else status = 'PASS';

    results.push({
      title: book.title,
      metadata: hasMetadata,
      cover: coverExists,
      coverSize,
      pdf: pdfExists,
      pdfSize,
      validPdf,
      pageCount,
      titleInPdf,
      brandingInPdf,
      wordCount,
      price: book.price,
      category: book.category,
      ageRange: `${book.age_min}-${book.age_max}`,
      slug: book.slug,
      status,
      issues,
    });
  }

  return results;
}

// ── Report ───────────────────────────────────────────────────

const results = validateAll();

console.log('\n=== LITTLEREADS EBOOK VALIDATION REPORT ===\n');

const passCount = results.filter(r => r.status === 'PASS').length;
const warnCount = results.filter(r => r.status === 'WARN').length;
const failCount = results.filter(r => r.status.startsWith('FAIL')).length;

console.log(`TOTAL: ${results.length} | PASS: ${passCount} | WARN: ${warnCount} | FAIL: ${failCount}\n`);

// Table
console.log(
  'TITLE | META | COVER | COVER SZ | PDF | PDF SZ | PAGES | TITLE✓ | BRAND✓ | STATUS'
);
console.log(
  '------|------|-------|----------|-----|--------|-------|--------|--------|--------'
);

for (const r of results) {
  console.log(
    `${r.title.substring(0, 38).padEnd(38)} | ` +
    `${r.metadata ? '✅' : '❌'} | ` +
    `${r.cover ? '✅' : '❌'} | ` +
    `${r.coverSize.padEnd(8)} | ` +
    `${r.pdf ? '✅' : '❌'} | ` +
    `${r.pdfSize.padEnd(7)} | ` +
    `${String(r.pageCount).padStart(5)} | ` +
    `${r.titleInPdf ? '✅' : '❌'} | ` +
    `${r.brandingInPdf ? '✅' : '❌'} | ` +
    `${r.status}`
  );
}

// Issues
const issuesFound = results.filter(r => r.issues.length > 0);
if (issuesFound.length > 0) {
  console.log('\n=== ISSUES ===');
  for (const r of issuesFound) {
    console.log(`  ${r.title}: ${r.issues.join('; ')}`);
  }
}

// Slug uniqueness
const slugs = results.map(r => r.slug);
const uniqueSlugs = new Set(slugs);
console.log(`\n=== SLUG CHECK ===`);
console.log(`Unique slugs: ${uniqueSlugs.size}/${slugs.length}`);
if (uniqueSlugs.size !== slugs.length) {
  console.log('WARNING: Duplicate slugs found!');
}

// Word count
const totalWords = results.reduce((sum, r) => sum + r.wordCount, 0);
console.log(`\n=== MANUSCRIPT WORD COUNTS ===`);
console.log(`Total description words across all books: ${totalWords}`);
for (const r of results) {
  console.log(`  ${r.title}: ~${r.wordCount} words (description; full manuscripts in PDFs)`);
}

// Page count summary
console.log(`\n=== PAGE COUNT SUMMARY ===`);
const totalPdfPages = results.reduce((sum, r) => sum + r.pageCount, 0);
console.log(`Total pages across all PDFs: ${totalPdfPages}`);
const minPages = Math.min(...results.map(r => r.pageCount));
const maxPages = Math.max(...results.map(r => r.pageCount));
console.log(`Range: ${minPages} – ${maxPages} pages per ebook`);

// Final verdict
console.log(`\n=== VERDICT ===`);
if (failCount > 0) {
  console.log(`❌ ${failCount} FAILED — review issues above`);
  process.exit(1);
} else if (warnCount > 0) {
  console.log(`⚠️  All ${results.length} ebooks PASS (with ${warnCount} warnings)`);
} else {
  console.log(`✅ All ${results.length}/20 ebooks PASS validation`);
}
